(* ::Package:: *)

LyndOrder[0]=0;
LyndOrder[u]=1;
LyndOrder[v]=2;
LyndOrder[w]=3;
LyndOrder[1-u]=4;
LyndOrder[1-v]=5;
LyndOrder[1-w]=6;
LyndOrder[yu]=7;
LyndOrder[yv]=8;
LyndOrder[yw]=9;
LyndOrder[_]=10;
LyndOrder[-1]=11;
LyndOrder[1]=12;
LyndOrder[1/yu]=13;
LyndOrder[1-1/yu]=14;
LyndOrder[1/yv]=15;
LyndOrder[1-1/yv]=16;
LyndOrder[1/(yu*yv)]=17;
LyndOrder[1-1/(yu*yv)]=18;

optimizeLyndonBasisReplacement[func_]:=Module[{lettersAppearing,letters},
  If[FreeQ[func,G],
    lettersAppearing=DeleteDuplicates[Select[DeleteDuplicates[Flatten[Reap[func/.HPL[aVec_,arg_]:>(Sow[letters[DeleteDuplicates[aVec],arg,Length[aVec]]];0)][[2]]]],Length[First[#]]>1&]/.letters[ll_,arg_,weight_]:>List[Sort[ll,LyndOrder[#1]<LyndOrder[#2]&],arg,Max[weight,5]]];
    Expand[func/.Join@@Table[Symbol["LyndRedReplacements"<>ToString[Length[lettersAppearing[[ii,1]]]]<>"Ew"<>ToString[lettersAppearing[[ii,3]]]<>"HPL"][lettersAppearing[[ii,2]]],{ii,Length[lettersAppearing]}]]
   ,lettersAppearing=DeleteDuplicates[Select[DeleteDuplicates[Flatten[Reap[func/.G[aVec_,arg_]:>(Sow[letters[DeleteDuplicates[aVec],arg,Length[aVec]]];0)][[2]]]],Length[First[#]]>1&]/.letters[ll_,arg_,weight_]:>List[Sort[ll,LyndOrder[#1]<LyndOrder[#2]&],arg,Max[weight,5]]];
    Expand[func/.Join@@Table[Symbol["LyndRedReplacements"<>ToString[Length[lettersAppearing[[ii,1]]]]<>"Ew"<>ToString[lettersAppearing[[ii,3]]]<>"G"][lettersAppearing[[ii,1]],lettersAppearing[[ii,2]]],{ii,Length[lettersAppearing]}]]]]

LyndRedReplacements2Ew5HPL[arg_]:=Module[{},LyndRedReplacements2Ew5HPL[temp_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements2Ew5HPL_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["HPL LyndRedReplacements loaded loaded for 2 letters at weight 5"]];
  LyndRedReplacements2Ew5HPL[arg]];
LyndRedReplacements2Ew6HPL[arg_]:=Module[{},LyndRedReplacements2Ew6HPL[temp_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements2Ew6HPL_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["HPL LyndRedReplacements loaded loaded for 2 letters at weight 6"]];
  LyndRedReplacements2Ew6HPL[arg]];
LyndRedReplacements2Ew7HPL[arg_]:=Module[{},LyndRedReplacements2Ew7HPL[temp_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements2Ew7HPL_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["HPL LyndRedReplacements loaded loaded for 2 letters at weight 7"]];
  LyndRedReplacements2Ew7HPL[arg]];
LyndRedReplacements2Ew8HPL[arg_]:=Module[{},LyndRedReplacements2Ew8HPL[temp_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements2Ew8HPL_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["HPL LyndRedReplacements loaded loaded for 2 letters at weight 8"]];
  LyndRedReplacements2Ew8HPL[arg]];
LyndRedReplacements2Ew9HPL[arg_]:=Module[{},LyndRedReplacements2Ew9HPL[temp_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements2Ew9HPL_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["HPL LyndRedReplacements loaded loaded for 2 letters at weight 9"]];
  LyndRedReplacements2Ew9HPL[arg]];
LyndRedReplacements2Ew10HPL[arg_]:=Module[{},LyndRedReplacements2Ew10HPL[temp_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements2Ew10HPL_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["HPL LyndRedReplacements loaded loaded for 2 letters at weight 10"]];
  LyndRedReplacements2Ew10HPL[arg]];

LyndRedReplacements3Ew5HPL[arg_]:=Module[{},LyndRedReplacements3Ew5HPL[temp_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements3Ew5HPL_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["HPL LyndRedReplacements loaded loaded for 3 letters at weight 5"]];
  LyndRedReplacements3Ew5HPL[arg]];
LyndRedReplacements3Ew6HPL[arg_]:=Module[{},LyndRedReplacements3Ew6HPL[temp_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements3Ew6HPL_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["HPL LyndRedReplacements loaded loaded for 3 letters at weight 6"]];
  LyndRedReplacements3Ew6HPL[arg]];
LyndRedReplacements3Ew7HPL[arg_]:=Module[{},LyndRedReplacements3Ew7HPL[temp_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements3Ew7HPL_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["HPL LyndRedReplacements loaded loaded for 3 letters at weight 7"]];
  LyndRedReplacements3Ew7HPL[arg]];
LyndRedReplacements3Ew8HPL[arg_]:=Module[{},LyndRedReplacements3Ew8HPL[temp_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements3Ew8HPL_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["HPL LyndRedReplacements loaded loaded for 3 letters at weight 8"]];
  LyndRedReplacements3Ew8HPL[arg]];
LyndRedReplacements3Ew9HPL[arg_]:=Module[{},LyndRedReplacements3Ew9HPL[temp_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements3Ew9HPL_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["HPL LyndRedReplacements loaded loaded for 3 letters at weight 9"]];
  LyndRedReplacements3Ew9HPL[arg]];
LyndRedReplacements3Ew10HPL[arg_]:=Module[{},LyndRedReplacements3Ew10HPL[temp_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements3Ew10HPL_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["HPL LyndRedReplacements loaded loaded for 3 letters at weight 10"]];
  LyndRedReplacements3Ew10HPL[arg]];

LyndRedReplacements2Ew5G[letters_,arg_]:=Module[{},LyndRedReplacements2Ew5G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements2Ew5G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 2 letters at weight 5"]];
  LyndRedReplacements2Ew5G[letters,arg]];
LyndRedReplacements2Ew6G[letters_,arg_]:=Module[{},LyndRedReplacements2Ew6G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements2Ew6G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 2 letters at weight 6"]];
  LyndRedReplacements2Ew6G[letters,arg]];
LyndRedReplacements2Ew7G[letters_,arg_]:=Module[{},LyndRedReplacements2Ew7G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements2Ew7G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 2 letters at weight 7"]];
  LyndRedReplacements2Ew7G[letters,arg]];
LyndRedReplacements2Ew8G[letters_,arg_]:=Module[{},LyndRedReplacements2Ew8G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements2Ew8G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 2 letters at weight 8"]];
  LyndRedReplacements2Ew8G[letters,arg]];
LyndRedReplacements2Ew9G[letters_,arg_]:=Module[{},LyndRedReplacements2Ew9G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements2Ew9G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 2 letters at weight 9"]];
  LyndRedReplacements2Ew9G[letters,arg]];
LyndRedReplacements2Ew10G[letters_,arg_]:=Module[{},LyndRedReplacements2Ew10G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements2Ew10G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 2 letters at weight 10"]];
  LyndRedReplacements2Ew10G[letters,arg]];

LyndRedReplacements3Ew5G[letters_,arg_]:=Module[{},LyndRedReplacements3Ew5G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements3Ew5G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 3 letters at weight 5"]];
  LyndRedReplacements3Ew5G[letters,arg]];
LyndRedReplacements3Ew6G[letters_,arg_]:=Module[{},LyndRedReplacements3Ew6G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements3Ew6G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 3 letters at weight 6"]];
  LyndRedReplacements3Ew6G[letters,arg]];
LyndRedReplacements3Ew7G[letters_,arg_]:=Module[{},LyndRedReplacements3Ew7G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements3Ew7G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 3 letters at weight 7"]];
  LyndRedReplacements3Ew7G[letters,arg]];
LyndRedReplacements3Ew8G[letters_,arg_]:=Module[{},LyndRedReplacements3Ew8G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements3Ew8G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 3 letters at weight 8"]];
  LyndRedReplacements3Ew8G[letters,arg]];
LyndRedReplacements3Ew9G[letters_,arg_]:=Module[{},LyndRedReplacements3Ew9G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements3Ew9G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 3 letters at weight 9"]];
  LyndRedReplacements3Ew9G[letters,arg]];
LyndRedReplacements3Ew10G[letters_,arg_]:=Module[{},LyndRedReplacements3Ew10G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements3Ew10G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 3 letters at weight 10"]];
  LyndRedReplacements3Ew10G[letters,arg]];

LyndRedReplacements4Ew5G[letters_,arg_]:=Module[{},LyndRedReplacements4Ew5G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements4Ew5G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 4 letters at weight 5"]];
  LyndRedReplacements4Ew5G[letters,arg]];
LyndRedReplacements4Ew6G[letters_,arg_]:=Module[{},LyndRedReplacements4Ew6G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements4Ew6G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 4 letters at weight 6"]];
  LyndRedReplacements4Ew6G[letters,arg]];
LyndRedReplacements4Ew7G[letters_,arg_]:=Module[{},LyndRedReplacements4Ew7G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements4Ew7G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 4 letters at weight 7"]];
  LyndRedReplacements4Ew7G[letters,arg]];
LyndRedReplacements4Ew8G[letters_,arg_]:=Module[{},LyndRedReplacements4Ew8G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements4Ew8G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 4 letters at weight 8"]];
  LyndRedReplacements4Ew8G[letters,arg]];
LyndRedReplacements4Ew9G[letters_,arg_]:=Module[{},LyndRedReplacements4Ew9G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements4Ew9G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 4 letters at weight 9"]];
  LyndRedReplacements4Ew9G[letters,arg]];
LyndRedReplacements4Ew10G[letters_,arg_]:=Module[{},LyndRedReplacements4Ew10G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements4Ew10G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 4 letters at weight 10"]];
  LyndRedReplacements4Ew10G[letters,arg]];

LyndRedReplacements5Ew5G[letters_,arg_]:=Module[{},LyndRedReplacements5Ew5G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements5Ew5G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 5 letters at weight 5"]];
  LyndRedReplacements5Ew5G[letters,arg]];
LyndRedReplacements5Ew6G[letters_,arg_]:=Module[{},LyndRedReplacements5Ew6G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements5Ew6G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 5 letters at weight 6"]];
  LyndRedReplacements5Ew6G[letters,arg]];
LyndRedReplacements5Ew7G[letters_,arg_]:=Module[{},LyndRedReplacements5Ew7G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements5Ew7G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 5 letters at weight 7"]];
  LyndRedReplacements5Ew7G[letters,arg]];
LyndRedReplacements5Ew8G[letters_,arg_]:=Module[{},LyndRedReplacements5Ew8G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements5Ew8G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 5 letters at weight 8"]];
  LyndRedReplacements5Ew8G[letters,arg]];
LyndRedReplacements5Ew9G[letters_,arg_]:=Module[{},LyndRedReplacements5Ew9G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements5Ew9G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 5 letters at weight 9"]];
  LyndRedReplacements5Ew9G[letters,arg]];
LyndRedReplacements5Ew10G[letters_,arg_]:=Module[{},LyndRedReplacements5Ew10G[temp1_,temp2_]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements5Ew10G_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["MPL LyndRedReplacements loaded loaded for 5 letters at weight 10"]];
  LyndRedReplacements5Ew10G[letters,arg]];
