(* ::Package:: *)

LyndOrder[0]=0;
LyndOrder[u]=1;
LyndOrder[v]=2;
LyndOrder[w]=3;
LyndOrder[1-u]=4;
LyndOrder[1-v]=5;
LyndOrder[1-w]=6;
LyndOrder[yu]=7;
LyndOrder[yv]=8;
LyndOrder[yw]=9;
LyndOrder[_]=10;
LyndOrder[-1]=11;
LyndOrder[1]=12;
LyndOrder[1/yu]=13;
LyndOrder[1-1/yu]=14;
LyndOrder[1/yv]=15;
LyndOrder[1-1/yv]=16;
LyndOrder[1/(yu*yv)]=17;
LyndOrder[1-1/(yu*yv)]=18;

GredL[{},b_]:=1;
HredL[{},b_]:=1;
GredL[A_,b_]:=GredL[A,b]=Block[{Atemp,vars,FFF}, 
  vars=FFF/@SortBy[Union[A],LyndOrder]; 
  Atemp=(FFF/@A)/. Thread[vars->Array[lyn,Length[vars]]]; 
  If[Length[vars]>1,Lin[Atemp]/.LyndRedReplacements[Length[vars],Max[Length[Atemp],5]]/. Thread[Array[lyn,Length[vars]]->vars]/. FFF[C__]:>C/.Lyn[B__]:>G[{B},b],G[A,b]]];
HredL[A_,b_]:=HredL[A,b]=Block[{Atemp,vars,FFF}, 
  vars=FFF/@SortBy[Union[A],LyndOrder]; 
  Atemp=(FFF/@A)/. Thread[vars->Array[lyn,Length[vars]]];
  If[Length[vars]>1,Lin[Atemp]/.LyndRedReplacements[Length[vars],Max[Length[Atemp],5]]/. Thread[Array[lyn,Length[vars]]->vars]/. FFF[C__]:>C/.Lyn[B__]:>HPL[{B},b],HPL[A,b]]];

LyndRedReplacements[2,5]:=Module[{},LyndRedReplacements[2,5]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements2Ew5_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 2 letters at weight 5"]];
  LyndRedReplacements[2,5]];
LyndRedReplacements[2,6]:=Module[{},LyndRedReplacements[2,6]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements2Ew6_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 2 letters at weight 6"]];
  LyndRedReplacements[2,6]];
LyndRedReplacements[2,7]:=Module[{},LyndRedReplacements[2,7]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements2Ew7_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 2 letters at weight 7"]];
  LyndRedReplacements[2,7]];
LyndRedReplacements[2,8]:=Module[{},LyndRedReplacements[2,8]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements2Ew8_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 2 letters at weight 8"]];
  LyndRedReplacements[2,8]];
LyndRedReplacements[2,9]:=Module[{},LyndRedReplacements[2,9]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements2Ew9_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 2 letters at weight 9"]];
  LyndRedReplacements[2,9]];
LyndRedReplacements[2,10]:=Module[{},LyndRedReplacements[2,10]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements2Ew10_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 2 letters at weight 10"]];
  LyndRedReplacements[2,10]];

LyndRedReplacements[3,5]:=Module[{},LyndRedReplacements[3,5]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements3Ew5_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 3 letters at weight 5"]];
  LyndRedReplacements[3,5]];
LyndRedReplacements[3,6]:=Module[{},LyndRedReplacements[3,6]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements3Ew6_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 3 letters at weight 6"]];
  LyndRedReplacements[3,6]];
LyndRedReplacements[3,7]:=Module[{},LyndRedReplacements[3,7]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements3Ew7_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 3 letters at weight 7"]];
  LyndRedReplacements[3,7]];
LyndRedReplacements[3,8]:=Module[{},LyndRedReplacements[3,8]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements3Ew8_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 3 letters at weight 8"]];
  LyndRedReplacements[3,8]];
LyndRedReplacements[3,9]:=Module[{},LyndRedReplacements[3,9]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements3Ew9_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 3 letters at weight 9"]];
  LyndRedReplacements[3,9]];
LyndRedReplacements[3,10]:=Module[{},LyndRedReplacements[3,10]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements3Ew10_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 3 letters at weight 10"]];
  LyndRedReplacements[3,10]];

LyndRedReplacements[4,5]:=Module[{},LyndRedReplacements[4,5]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements4Ew5_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 4 letters at weight 5"]];
  LyndRedReplacements[4,5]];
LyndRedReplacements[4,6]:=Module[{},LyndRedReplacements[4,6]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements4Ew6_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 4 letters at weight 6"]];
  LyndRedReplacements[4,6]];
LyndRedReplacements[4,7]:=Module[{},LyndRedReplacements[4,7]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements4Ew7_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 4 letters at weight 7"]];
  LyndRedReplacements[4,7]];
LyndRedReplacements[4,8]:=Module[{},LyndRedReplacements[4,8]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements4Ew8_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 4 letters at weight 8"]];
  LyndRedReplacements[4,8]];
LyndRedReplacements[4,9]:=Module[{},LyndRedReplacements[4,9]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements4Ew9_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 4 letters at weight 9"]];
  LyndRedReplacements[4,9]];
LyndRedReplacements[4,10]:=Module[{},LyndRedReplacements[4,10]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements4Ew10_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 4 letters at weight 10"]];
  LyndRedReplacements[4,10]];

LyndRedReplacements[5,5]:=Module[{},LyndRedReplacements[5,5]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements5Ew5_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 5 letters at weight 5"]];
  LyndRedReplacements[5,5]];
LyndRedReplacements[5,6]:=Module[{},LyndRedReplacements[5,6]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements5Ew6_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 5 letters at weight 6"]];
  LyndRedReplacements[5,6]];
LyndRedReplacements[5,7]:=Module[{},LyndRedReplacements[5,7]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements5Ew7_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 5 letters at weight 7"]];
  LyndRedReplacements[5,7]];
LyndRedReplacements[5,8]:=Module[{},LyndRedReplacements[5,8]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements5Ew8_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 5 letters at weight 8"]];
  LyndRedReplacements[5,8]];
LyndRedReplacements[5,9]:=Module[{},LyndRedReplacements[5,9]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements5Ew9_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 5 letters at weight 9"]];
  LyndRedReplacements[5,9]];
LyndRedReplacements[5,10]:=Module[{},LyndRedReplacements[5,10]=.;
  Get[$MathematicaLibrary<>"/Function Library/Identities/LyndRed/Local Binaries/LyndRedReplacements5Ew10_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["LyndRedReplacements loaded loaded for 5 letters at weight 10"]];
  LyndRedReplacements[5,10]];
