(* ::Package:: *)

toLineE[DS3[a_],{u,1-u}]:=Module[{},toLineE[DS3[temp1_],{u,1-u}]=.;
  toLineE[DS4[temp1_],{u,1-u}]=.;
  toLineE[DS5[temp1_],{u,1-u}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_5_euclidean_DS_uomu_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DS uomu euclidean lines loaded"]];
  toLineE[DS3[a],{u,1-u}]];
toLineE[DS4[a_],{u,1-u}]:=Module[{},toLineE[DS3[temp1_],{u,1-u}]=.;
  toLineE[DS4[temp1_],{u,1-u}]=.;
  toLineE[DS5[temp1_],{u,1-u}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_5_euclidean_DS_uomu_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DS uomu euclidean lines loaded"]];
  toLineE[DS4[a],{u,1-u}]];
toLineE[DS5[a_],{u,1-u}]:=Module[{},toLineE[DS3[temp1_],{u,1-u}]=.;
  toLineE[DS4[temp1_],{u,1-u}]=.;
  toLineE[DS5[temp1_],{u,1-u}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_5_euclidean_DS_uomu_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DS uomu euclidean lines loaded"]];
  toLineE[DS5[a],{u,1-u}]];
toLineE[DS6[a_],{u,1-u}]:=Module[{},toLineE[DS6[temp1_],{u,1-u}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_6_euclidean_DS_uomu_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 DS uomu euclidean lines loaded"]];
  toLineE[DS6[a],{u,1-u}]];
toLineE[DS7[a_],{u,1-u}]:=Module[{},toLineE[DS7[temp1_],{u,1-u}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_7_euclidean_DS_uomu_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 DS uomu euclidean lines loaded"]];
  toLineE[DS7[a],{u,1-u}]];
toLineE[DS8[a_],{u,1-u}]:=Module[{},toLineE[DS8[temp1_],{u,1-u}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_8_euclidean_DS_uomu_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 8 DS uomu euclidean lines loaded"]];
  toLineE[DS8[a],{u,1-u}]];

toLineE[DS3[a_],{u,0}]:=Module[{},toLineE[DS3[temp1_],{u,0}]=.;
  toLineE[DS4[temp1_],{u,0}]=.;
  toLineE[DS5[temp1_],{u,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_5_euclidean_DS_u0_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DS u0 euclidean lines loaded"]];
  toLineE[DS3[a],{u,0}]];
toLineE[DS4[a_],{u,0}]:=Module[{},toLineE[DS3[temp1_],{u,0}]=.;
  toLineE[DS4[temp1_],{u,0}]=.;
  toLineE[DS5[temp1_],{u,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_5_euclidean_DS_u0_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DS u0 euclidean lines loaded"]];
  toLineE[DS4[a],{u,0}]];
toLineE[DS5[a_],{u,0}]:=Module[{},toLineE[DS3[temp1_],{u,0}]=.;
  toLineE[DS4[temp1_],{u,0}]=.;
  toLineE[DS5[temp1_],{u,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_5_euclidean_DS_u0_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DS u0 euclidean lines loaded"]];
  toLineE[DS5[a],{u,0}]];
toLineE[DS6[a_],{u,0}]:=Module[{},toLineE[DS6[temp1_],{u,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_6_euclidean_DS_u0_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 DS u0 euclidean lines loaded"]];
  toLineE[DS6[a],{u,0}]];
toLineE[DS7[a_],{u,0}]:=Module[{},toLineE[DS7[temp1_],{u,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_7_euclidean_DS_u0_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 DS u0 euclidean lines loaded"]];
  toLineE[DS7[a],{u,0}]];
toLineE[DS8[a_],{u,0}]:=Module[{},toLineE[DS8[temp1_],{u,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_8_euclidean_DS_u0_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 8 DS u0 euclidean lines loaded"]];
  toLineE[DS8[a],{u,0}]];

toLineE[DS3[a_],{u,1}]:=Module[{},toLineE[DS3[temp1_],{u,1}]=.;
  toLineE[DS4[temp1_],{u,1}]=.;
  toLineE[DS5[temp1_],{u,1}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_5_euclidean_DS_u1_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DS u1 euclidean lines loaded"]];
  toLineE[DS3[a],{u,1}]];
toLineE[DS4[a_],{u,1}]:=Module[{},toLineE[DS3[temp1_],{u,1}]=.;
  toLineE[DS4[temp1_],{u,1}]=.;
  toLineE[DS5[temp1_],{u,1}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_5_euclidean_DS_u1_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DS u1 euclidean lines loaded"]];
  toLineE[DS4[a],{u,1}]];
toLineE[DS5[a_],{u,1}]:=Module[{},toLineE[DS3[temp1_],{u,1}]=.;
  toLineE[DS4[temp1_],{u,1}]=.;
  toLineE[DS5[temp1_],{u,1}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_5_euclidean_DS_u1_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DS u1 euclidean lines loaded"]];
  toLineE[DS5[a],{u,1}]];
toLineE[DS6[a_],{u,1}]:=Module[{},toLineE[DS6[temp1_],{u,1}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_6_euclidean_DS_u1_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 DS u1 euclidean lines loaded"]];
  toLineE[DS6[a],{u,1}]];
toLineE[DS7[a_],{u,1}]:=Module[{},toLineE[DS7[temp1_],{u,1}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_7_euclidean_DS_u1_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 DS u1 euclidean lines loaded"]];
  toLineE[DS7[a],{u,1}]];
toLineE[DS8[a_],{u,1}]:=Module[{},toLineE[DS8[temp1_],{u,1}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_8_euclidean_DS_u1_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 8 DS u1 euclidean lines loaded"]];
  toLineE[DS8[a],{u,1}]];

toLineE[DS3[a_],{0,w}]:=Module[{},toLineE[DS3[temp1_],{0,w}]=.;
  toLineE[DS4[temp1_],{0,w}]=.;
  toLineE[DS5[temp1_],{0,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_5_euclidean_DS_0w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DS 0w euclidean lines loaded"]];
  toLineE[DS3[a],{0,w}]];
toLineE[DS4[a_],{0,w}]:=Module[{},toLineE[DS3[temp1_],{0,w}]=.;
  toLineE[DS4[temp1_],{0,w}]=.;
  toLineE[DS5[temp1_],{0,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_5_euclidean_DS_0w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DS 0w euclidean lines loaded"]];
  toLineE[DS4[a],{0,w}]];
toLineE[DS5[a_],{0,w}]:=Module[{},toLineE[DS3[temp1_],{0,w}]=.;
  toLineE[DS4[temp1_],{0,w}]=.;
  toLineE[DS5[temp1_],{0,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_5_euclidean_DS_0w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DS 0w euclidean lines loaded"]];
  toLineE[DS5[a],{0,w}]];
toLineE[DS6[a_],{0,w}]:=Module[{},toLineE[DS6[temp1_],{0,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_6_euclidean_DS_0w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 DS 0w euclidean lines loaded"]];
  toLineE[DS6[a],{0,w}]];
toLineE[DS7[a_],{0,w}]:=Module[{},toLineE[DS7[temp1_],{0,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_7_euclidean_DS_0w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 DS 0w euclidean lines loaded"]];
  toLineE[DS7[a],{0,w}]];
toLineE[DS8[a_],{0,w}]:=Module[{},toLineE[DS8[temp1_],{0,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_8_euclidean_DS_0w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 8 DS 0w euclidean lines loaded"]];
  toLineE[DS8[a],{0,w}]];

toLineE[DS3[a_],{1,w}]:=Module[{},toLineE[DS3[temp1_],{1,w}]=.;
  toLineE[DS4[temp1_],{1,w}]=.;
  toLineE[DS5[temp1_],{1,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_5_euclidean_DS_1w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DS 1w euclidean lines loaded"]];
  toLineE[DS3[a],{1,w}]];
toLineE[DS4[a_],{1,w}]:=Module[{},toLineE[DS3[temp1_],{1,w}]=.;
  toLineE[DS4[temp1_],{1,w}]=.;
  toLineE[DS5[temp1_],{1,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_5_euclidean_DS_1w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DS 1w euclidean lines loaded"]];
  toLineE[DS4[a],{1,w}]];
toLineE[DS5[a_],{1,w}]:=Module[{},toLineE[DS3[temp1_],{1,w}]=.;
  toLineE[DS4[temp1_],{1,w}]=.;
  toLineE[DS5[temp1_],{1,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_5_euclidean_DS_1w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DS 1w euclidean lines loaded"]];
  toLineE[DS5[a],{1,w}]];
toLineE[DS6[a_],{1,w}]:=Module[{},toLineE[DS6[temp1_],{1,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_6_euclidean_DS_1w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 DS 1w euclidean lines loaded"]];
  toLineE[DS6[a],{1,w}]];
toLineE[DS7[a_],{1,w}]:=Module[{},toLineE[DS7[temp1_],{1,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_7_euclidean_DS_1w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 DS 1w euclidean lines loaded"]];
  toLineE[DS7[a],{1,w}]];
toLineE[DS8[a_],{1,w}]:=Module[{},toLineE[DS8[temp1_],{1,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_8_euclidean_DS_1w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 8 DS 1w euclidean lines loaded"]];
  toLineE[DS8[a],{1,w}]];

toLineE[DS3[a_],{0,0}]:=Module[{},toLineE[DS3[temp1_],{0,0}]=.;
  toLineE[DS4[temp1_],{0,0}]=.;
  toLineE[DS5[temp1_],{0,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_5_euclidean_DS_00_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DS 00 euclidean lines loaded"]];
  toLineE[DS3[a],{0,0}]];
toLineE[DS4[a_],{0,0}]:=Module[{},toLineE[DS3[temp1_],{0,0}]=.;
  toLineE[DS4[temp1_],{0,0}]=.;
  toLineE[DS5[temp1_],{0,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_5_euclidean_DS_00_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DS 00 euclidean lines loaded"]];
  toLineE[DS4[a],{0,0}]];
toLineE[DS5[a_],{0,0}]:=Module[{},toLineE[DS3[temp1_],{0,0}]=.;
  toLineE[DS4[temp1_],{0,0}]=.;
  toLineE[DS5[temp1_],{0,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_5_euclidean_DS_00_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DS 00 euclidean lines loaded"]];
  toLineE[DS5[a],{0,0}]];
toLineE[DS6[a_],{0,0}]:=Module[{},toLineE[DS6[temp1_],{0,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_6_euclidean_DS_00_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 DS 00 euclidean lines loaded"]];
  toLineE[DS6[a],{0,0}]];
toLineE[DS7[a_],{0,0}]:=Module[{},toLineE[DS7[temp1_],{0,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_7_euclidean_DS_00_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 DS 00 euclidean lines loaded"]];
  toLineE[DS7[a],{0,0}]];
toLineE[DS8[a_],{0,0}]:=Module[{},toLineE[DS8[temp1_],{0,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DS Limits/Local Binaries/weight_8_euclidean_DS_00_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 8 DS 00 euclidean lines loaded"]];
  toLineE[DS8[a],{0,0}]];

(*toLineE[func_,{1,0,w}]:=(toLineE[func,{1,0,w}]=toLineE[toSurfaceE[func,v->0],{1,0,w}])/;!FreeQ[func,Alternatives[H3[_],H4[_],H5[_],H6[_],E7[_],O7[_],E8[_],O8[_],E9[_],O9[_]]];*)

toLineE[func_,{u,0,1}]:=(toLineE[func,{u,0,1}]=Expand[func/.irreducibleDoubleScalingFunctionsToLineE[{u,0,1}]/.flipArgument[w]/.{HPL[{___,1},1-w]->0,HPL[{0},w]->Log[w]}])/;FreeQ[func,Alternatives[H3[_],H4[_],H5[_],H6[_],E7[_],O7[_],E8[_],O8[_],E9[_],O9[_]]];
toLineE[func_,{1,0,w}]:=(toLineE[func,{1,0,w}]=Expand[func/.irreducibleDoubleScalingFunctionsToLineE[{1,0,w}]/.flipArgument[u]/.{HPL[{___,1},1-u]->0,HPL[{0},u]->Log[u]}])/;FreeQ[func,Alternatives[H3[_],H4[_],H5[_],H6[_],E7[_],O7[_],E8[_],O8[_],E9[_],O9[_]]];
toLineE[func_,{u,0,1-u}]:=(toLineE[func,{u,0,1-u}]:=Expand[func/.irreducibleDoubleScalingFunctionsToLineE[{u,0,1-u}]/.{w->1-u}/.flipArgument[1-u]])/;FreeQ[func,Alternatives[H3[_],H4[_],H5[_],H6[_],E7[_],O7[_],E8[_],O8[_],E9[_],O9[_]]];
toLineE[func_,{u,0,0}]:=(toLineE[func,{u,0,0}]=Expand[func/.irreducibleDoubleScalingFunctionsToLineE[{u,0,0}]/.flipArgument[{1-u,1-w}]/.HPL[{___,1},w]->0/.HPL[{0},a_]:>Log[a]])/;FreeQ[func,Alternatives[H3[_],H4[_],H5[_],H6[_],E7[_],O7[_],E8[_],O8[_],E9[_],O9[_]]];

toLineEc[func_,{u,0,1}]:=toLineEc[func,{u,0,1}]=Expand[IntegrateHPL[coproductD[func,u]/.irreducibleDoubleScalingFunctionsToLineE[{u,0,1}]/.Power[1-u-w,-1]->Power[-u,-1]/.flipArgument[w]/.{HPL[{___,1},1-w]->0,HPL[{0},1-w]->Log[1-w]},{u,1,u}]];
toLineEc[func_,{1,0,w}]:=toLineEc[func,{1,0,w}]=Expand[IntegrateHPL[coproductD[func,w]/.irreducibleDoubleScalingFunctionsToLineE[{1,0,w}]/.Power[1-u-w,-1]->Power[-w,-1]/.flipArgument[u]/.{HPL[{___,1},1-u]->0,HPL[{0},1-u]->Log[1-u]},{w,1,w}]];
toLineEc[func_,{u,0,1-u}]:=toLineEc[func,{u,0,1-u}]=Module[{functionalForm}, functionalForm=Expand[IntegrateHPL[Expand[(coproductD[func,u]-coproductD[func,w])/.{w->1-u}/.irreducibleDoubleScalingFunctionsToLineE[{u,0,1-u}]/.flipArgument[1-u]],{u,0,u}]]; Expand[functionalForm+toPointE[func,{u,0,1},u->0]-(functionalForm/.HPL[{___,1},u]->0)]];
toLineEc[func_,{u,0,0}]:=toLineEc[func,{u,0,0}]=Module[{functionalForm}, functionalForm=Expand[IntegrateHPL[coproductD[func,u]/.irreducibleDoubleScalingFunctionsToLineE[{u,0,0}]/.flipArgument[1-w]/.HPL[{___,1},w]->0/.Power[1-u-w,-1]->Power[1-u,-1],{u,1,u}]]; Expand[(functionalForm+toPointE[func,{1,0,w},w->0]-(functionalForm/.flipArgument[u]/.HPL[{___,1},1-u]->0))/.flipArgument[{1-u,1-v,1-w}]/.HPL[{0},a_]:>Log[a]]];

toPointE[func_,{u,0,1},u->0]:=toLineE[func,{u,0,1}]/.flipArgument[1-u]/.{HPL[{___,1},u]->0};
toPointE[func_,{1,0,w},w->0]:=toLineE[func,{1,0,w}]/.flipArgument[1-w]/.{HPL[{___,1},w]->0};
