(* ::Package:: *)

EMRK[func_,var_->1]:=0/;OddQ[yGrading[func]]

EMRK[H3[a_],u->1]:=Module[{},EMRK[H3[temp_],u->1]=.;
  EMRK[H4[temp_],u->1]=.;
  EMRK[H5[temp_],u->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_5_irreducible_EMRK_limits_uTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 irreducible EMRK u->1 limits loaded"]];
  EMRK[H3[a],u->1]];
EMRK[H4[a_],u->1]:=Module[{},EMRK[H3[temp_],u->1]=.;
  EMRK[H4[temp_],u->1]=.;
  EMRK[H5[temp_],u->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_5_irreducible_EMRK_limits_uTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 irreducible EMRK u->1 limits loaded"]];
  EMRK[H4[a],u->1]];
EMRK[H5[a_],u->1]:=Module[{},EMRK[H3[temp_],u->1]=.;
  EMRK[H4[temp_],u->1]=.;
  EMRK[H5[temp_],u->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_5_irreducible_EMRK_limits_uTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 irreducible EMRK u->1 limits loaded"]];
  EMRK[H5[a],u->1]];
EMRK[H6[a_],u->1]:=Module[{},EMRK[H6[temp_],u->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_6_irreducible_EMRK_limits_uTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 irreducible EMRK u->1 limits loaded"]];
  EMRK[H6[a],u->1]];
EMRK[E7[a_],u->1]:=Module[{},EMRK[E7[temp_],u->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_7_irreducible_even_EMRK_limits_uTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 irreducible EMRK u->1 limits loaded"]];
  EMRK[E7[a],u->1]];

EMRK[H3[a_],v->1]:=Module[{},EMRK[H3[temp_],v->1]=.;
  EMRK[H4[temp_],v->1]=.;
  EMRK[H5[temp_],v->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_5_irreducible_EMRK_limits_vTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 irreducible EMRK v->1 limits loaded"]];
  EMRK[H3[a],v->1]];
EMRK[H4[a_],v->1]:=Module[{},EMRK[H3[temp_],v->1]=.;
  EMRK[H4[temp_],v->1]=.;
  EMRK[H5[temp_],v->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_5_irreducible_EMRK_limits_vTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 irreducible EMRK v->1 limits loaded"]];
  EMRK[H4[a],v->1]];
EMRK[H5[a_],v->1]:=Module[{},EMRK[H3[temp_],v->1]=.;
  EMRK[H4[temp_],v->1]=.;
  EMRK[H5[temp_],v->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_5_irreducible_EMRK_limits_vTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 irreducible EMRK v->1 limits loaded"]];
  EMRK[H5[a],v->1]];
EMRK[H6[a_],v->1]:=Module[{},EMRK[H6[temp_],v->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_6_irreducible_EMRK_limits_vTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 irreducible EMRK v->1 limits loaded"]];
  EMRK[H6[a],v->1]];
EMRK[E7[a_],v->1]:=Module[{},EMRK[E7[temp_],v->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_7_irreducible_even_EMRK_limits_vTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 irreducible EMRK v->1 limits loaded"]];
  EMRK[E7[a],v->1]];

EMRK[H3[a_],w->1]:=Module[{},EMRK[H3[temp_],w->1]=.;
  EMRK[H4[temp_],w->1]=.;
  EMRK[H5[temp_],w->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_5_irreducible_EMRK_limits_wTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 irreducible EMRK w->1 limits loaded"]];
  EMRK[H3[a],w->1]];
EMRK[H4[a_],w->1]:=Module[{},EMRK[H3[temp_],w->1]=.;
  EMRK[H4[temp_],w->1]=.;
  EMRK[H5[temp_],w->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_5_irreducible_EMRK_limits_wTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 irreducible EMRK w->1 limits loaded"]];
  EMRK[H4[a],w->1]];
EMRK[H5[a_],w->1]:=Module[{},EMRK[H3[temp_],w->1]=.;
  EMRK[H4[temp_],w->1]=.;
  EMRK[H5[temp_],w->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_5_irreducible_EMRK_limits_wTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 irreducible EMRK w->1 limits loaded"]];
  EMRK[H5[a],w->1]];
EMRK[H6[a_],w->1]:=Module[{},EMRK[H6[temp_],w->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_6_irreducible_EMRK_limits_wTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 irreducible EMRK w->1 limits loaded"]];
  EMRK[H6[a],w->1]];
EMRK[E7[a_],w->1]:=Module[{},EMRK[E7[temp_],w->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_7_irreducible_even_EMRK_limits_wTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 irreducible EMRK w->1 limits loaded"]];
  EMRK[E7[a],w->1]];

MRK[H3[a_],u->1]:=Module[{},MRK[H3[temp_],u->1]=.;
  MRK[H4[temp_],u->1]=.;
  MRK[H5[temp_],u->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_5_irreducible_MRK_limits_uTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 irreducible MRK u->1 limits loaded"]];
  MRK[H3[a],u->1]];
MRK[H4[a_],u->1]:=Module[{},MRK[H3[temp_],u->1]=.;
  MRK[H4[temp_],u->1]=.;
  MRK[H5[temp_],u->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_5_irreducible_MRK_limits_uTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 irreducible MRK u->1 limits loaded"]];
  MRK[H4[a],u->1]];
MRK[H5[a_],u->1]:=Module[{},MRK[H3[temp_],u->1]=.;
  MRK[H4[temp_],u->1]=.;
  MRK[H5[temp_],u->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_5_irreducible_MRK_limits_uTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 irreducible MRK u->1 limits loaded"]];
  MRK[H5[a],u->1]];
MRK[H6[a_],u->1]:=Module[{},MRK[H6[temp_],u->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_6_irreducible_MRK_limits_uTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 irreducible MRK u->1 limits loaded"]];
  MRK[H6[a],u->1]];
MRK[E7[a_],u->1]:=Module[{},MRK[E7[temp_],u->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_7_irreducible_even_MRK_limits_uTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 irreducible even MRK u->1 limits loaded"]];
  MRK[E7[a],u->1]];
MRK[O7[a_],u->1]:=Module[{},MRK[O7[temp_],u->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_7_irreducible_odd_MRK_limits_uTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 irreducible odd MRK u->1 limits loaded"]];
  MRK[O7[a],u->1]];

MRK[H3[a_],v->1]:=Module[{},MRK[H3[temp_],v->1]=.;
  MRK[H4[temp_],v->1]=.;
  MRK[H5[temp_],v->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_5_irreducible_MRK_limits_vTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 irreducible MRK v->1 limits loaded"]];
  MRK[H3[a],v->1]];
MRK[H4[a_],v->1]:=Module[{},MRK[H3[temp_],v->1]=.;
  MRK[H4[temp_],v->1]=.;
  MRK[H5[temp_],v->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_5_irreducible_MRK_limits_vTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 irreducible MRK v->1 limits loaded"]];
  MRK[H4[a],v->1]];
MRK[H5[a_],v->1]:=Module[{},MRK[H3[temp_],v->1]=.;
  MRK[H4[temp_],v->1]=.;
  MRK[H5[temp_],v->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_5_irreducible_MRK_limits_vTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 irreducible MRK v->1 limits loaded"]];
  MRK[H5[a],v->1]];
MRK[H6[a_],v->1]:=Module[{},MRK[H6[temp_],v->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_6_irreducible_MRK_limits_vTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 irreducible MRK v->1 limits loaded"]];
  MRK[H6[a],v->1]];
MRK[E7[a_],v->1]:=Module[{},MRK[E7[temp_],v->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_7_irreducible_even_MRK_limits_vTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 irreducible even MRK v->1 limits loaded"]];
  MRK[E7[a],v->1]];
MRK[O7[a_],v->1]:=Module[{},MRK[O7[temp_],v->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_7_irreducible_odd_MRK_limits_vTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 irreducible odd MRK v->1 limits loaded"]];
  MRK[O7[a],v->1]];

MRK[H3[a_],w->1]:=Module[{},MRK[H3[temp_],w->1]=.;
  MRK[H4[temp_],w->1]=.;
  MRK[H5[temp_],w->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_5_irreducible_MRK_limits_wTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 irreducible MRK w->1 limits loaded"]];
  MRK[H3[a],w->1]];
MRK[H4[a_],w->1]:=Module[{},MRK[H3[temp_],w->1]=.;
  MRK[H4[temp_],w->1]=.;
  MRK[H5[temp_],w->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_5_irreducible_MRK_limits_wTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 irreducible MRK w->1 limits loaded"]];
  MRK[H4[a],w->1]];
MRK[H5[a_],w->1]:=Module[{},MRK[H3[temp_],w->1]=.;
  MRK[H4[temp_],w->1]=.;
  MRK[H5[temp_],w->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_5_irreducible_MRK_limits_wTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 irreducible MRK w->1 limits loaded"]];
  MRK[H5[a],w->1]];
MRK[H6[a_],w->1]:=Module[{},MRK[H6[temp_],w->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_6_irreducible_MRK_limits_wTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 irreducible MRK w->1 limits loaded"]];
  MRK[H6[a],w->1]];
MRK[E7[a_],w->1]:=Module[{},MRK[E7[temp_],w->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_7_irreducible_even_MRK_limits_wTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 irreducible even MRK w->1 limits loaded"]];
  MRK[E7[a],w->1]];
MRK[O7[a_],w->1]:=Module[{},MRK[O7[temp_],w->1]=.;
  Get[$MathematicaLibrary<>"/Function Library/MRK/Local Binaries/weight_7_irreducible_odd_MRK_limits_wTo1_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 irreducible odd MRK w->1 limits loaded"]];
  MRK[O7[a],w->1]];
