(* ::Package:: *)

V6[0] = 1;
V6[1] := Module[{},V6[1]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/V61_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["V6[1] loaded"]];
  V6[1]];
V6[2] := Module[{},V6[2]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/V62_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["V6[2] loaded"]];
  V6[2]];
V6[3] := Module[{},V6[3]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/V63_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["V6[3] loaded"]];
  V6[3]];
V6[4] := Module[{},V6[4]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/V64_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["V6[4] loaded"]];
  V6[4]];
  
Vt6[0] = 0;
Vt6[1] = 0;
Vt6[2] := Module[{},Vt6[2]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/Vt62_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["Vt6[2] loaded"]];
  Vt6[2]];
Vt6[3] := Module[{},Vt6[3]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/Vt63_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["Vt6[3] loaded"]];
  Vt6[3]];
Vt6[4] := Module[{},Vt6[4]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/Vt64_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["Vt6[4] loaded"]];
  Vt6[4]];
  
E6[0] = 1;
E6[1] := Module[{},E6[1]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/E61_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["E6[1] loaded"]];
  E6[1]];
E6[2] := Module[{},E6[2]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/E62_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["E6[2] loaded"]];
  E6[2]];
E6[3] := Module[{},E6[3]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/E63_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["E6[3] loaded"]];
  E6[3]];
E6[4] := Module[{},E6[4]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/E64_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["E6[4] loaded"]];
  E6[4]];
  
Et6[0] = 0;
Et6[1] = 0;
Et6[2] := Module[{},Et6[2]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/Et62_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["Et6[2] loaded"]];
  Et6[2]];
Et6[3] := Module[{},Et6[3]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/Et63_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["Et6[3] loaded"]];
  Et6[3]];
Et6[4] := Module[{},Et6[4]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/Et64_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["Et6[4] loaded"]];
  Et6[4]];
  
U6[0] = 0;
U6[1] := Module[{},U6[1]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/U61_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["U6[1] loaded"]];
  U6[1]];
U6[2] := Module[{},U6[2]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/U62_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["U6[2] loaded"]];
  U6[2]];
U6[3] := Module[{},U6[3]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/U63_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["U6[3] loaded"]];
  U6[3]];
U6[4] := Module[{},U6[4]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/U64_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["U6[4] loaded"]];
  U6[4]];