(* ::Package:: *)

V6[0] = 1;
V6[1] := Module[{},V6[1]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/V61_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["V6[1] loaded"]];
  V6[1]];
V6[2] := Module[{},V6[2]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/V62_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["V6[2] loaded"]];
  V6[2]];
V6[3] := Module[{},V6[3]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/V63_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["V6[3] loaded"]];
  V6[3]];
V6[4] := Module[{},V6[4]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/V64_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["V6[4] loaded"]];
  V6[4]];
  
Vt6[0] = 0;
Vt6[1] = 0;
Vt6[2] := Module[{},Vt6[2]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/Vt62_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["Vt6[2] loaded"]];
  Vt6[2]];
Vt6[3] := Module[{},Vt6[3]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/Vt63_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["Vt6[3] loaded"]];
  Vt6[3]];
Vt6[4] := Module[{},Vt6[4]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/Vt64_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["Vt6[4] loaded"]];
  Vt6[4]];
  
hexagonE[0] = 1;
hexagonE[1] := Module[{},hexagonE[1]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/hexagonE[1]_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["hexagonE[1] loaded"]];
  hexagonE[1]];
hexagonE[2] := Module[{},hexagonE[2]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/hexagonE[2]_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["hexagonE[2] loaded"]];
  hexagonE[2]];
hexagonE[3] := Module[{},hexagonE[3]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/hexagonE[3]_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["hexagonE[3] loaded"]];
  hexagonE[3]];
hexagonE[4] := Module[{},hexagonE[4]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/hexagonE[4]_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["hexagonE[4] loaded"]];
  hexagonE[4]];
  
hexagonEt[0] = 0;
hexagonEt[1] = 0;
hexagonEt[2] := Module[{},hexagonEt[2]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/hexagonEt[2]_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["hexagonEt[2] loaded"]];
  hexagonEt[2]];
hexagonEt[3] := Module[{},hexagonEt[3]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/hexagonEt[3]_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["hexagonEt[3] loaded"]];
  hexagonEt[3]];
hexagonEt[4] := Module[{},hexagonEt[4]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/hexagonEt[4]_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["hexagonEt[4] loaded"]];
  hexagonEt[4]];
  
U6[0] = 0;
U6[1] := Module[{},U6[1]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/U61_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["U6[1] loaded"]];
  U6[1]];
U6[2] := Module[{},U6[2]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/U62_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["U6[2] loaded"]];
  U6[2]];
U6[3] := Module[{},U6[3]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/U63_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["U6[3] loaded"]];
  U6[3]];
U6[4] := Module[{},U6[4]=.;
  Get[$MathematicaLibrary<>"/Function Library/Six Points/Local Binaries/U64_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["U6[4] loaded"]];
  U6[4]];
