(* ::Package:: *)

toLineE[DT3[a_],{u,0}]:=Module[{},toLineE[DT3[temp1_],{u,0}]=.;
  toLineE[DT4[temp1_],{u,0}]=.;
  toLineE[DT5[temp1_],{u,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_5_euclidean_DT_u0_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 u0 euclidean lines loaded"]];
  toLineE[DT3[a],{u,0}]];
toLineE[DT4[a_],{u,0}]:=Module[{},toLineE[DT3[temp1_],{u,0}]=.;
  toLineE[DT4[temp1_],{u,0}]=.;
  toLineE[DT5[temp1_],{u,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_5_euclidean_DT_u0_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 u0 euclidean lines loaded"]];
  toLineE[DT4[a],{u,0}]];
toLineE[DT5[a_],{u,0}]:=Module[{},toLineE[DT3[temp1_],{u,0}]=.;
  toLineE[DT4[temp1_],{u,0}]=.;
  toLineE[DT5[temp1_],{u,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_5_euclidean_DT_u0_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 u0 euclidean lines loaded"]];
  toLineE[DT5[a],{u,0}]];
toLineE[DT6[a_],{u,0}]:=Module[{},toLineE[DT6[temp1_],{u,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_6_euclidean_DT_u0_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 u0 euclidean lines loaded"]];
  toLineE[DT6[a],{u,0}]];
toLineE[DT7[a_],{u,0}]:=Module[{},toLineE[DT7[temp1_],{u,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_7_euclidean_DT_u0_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 DT even u0 euclidean lines loaded"]];
  toLineE[DT7[a],{u,0}]];
toLineE[DT8[a_],{u,0}]:=Module[{},toLineE[DT8[temp1_],{u,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_8_euclidean_DT_u0_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 8 DT even u0 euclidean lines loaded"]];
  toLineE[DT8[a],{u,0}]];

toLineE[DT3[a_],{u,1}]:=Module[{},toLineE[DT3[temp1_],{u,1}]=.;
  toLineE[DT4[temp1_],{u,1}]=.;
  toLineE[DT5[temp1_],{u,1}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_5_euclidean_DT_u1_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 u1 euclidean lines loaded"]];
  toLineE[DT3[a],{u,1}]];
toLineE[DT4[a_],{u,1}]:=Module[{},toLineE[DT3[temp1_],{u,1}]=.;
  toLineE[DT4[temp1_],{u,1}]=.;
  toLineE[DT5[temp1_],{u,1}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_5_euclidean_DT_u1_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 u1 euclidean lines loaded"]];
  toLineE[DT4[a],{u,1}]];
toLineE[DT5[a_],{u,1}]:=Module[{},toLineE[DT3[temp1_],{u,1}]=.;
  toLineE[DT4[temp1_],{u,1}]=.;
  toLineE[DT5[temp1_],{u,1}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_5_euclidean_DT_u1_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 u1 euclidean lines loaded"]];
  toLineE[DT5[a],{u,1}]];
toLineE[DT6[a_],{u,1}]:=Module[{},toLineE[DT6[temp1_],{u,1}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_6_euclidean_DT_u1_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 u1 euclidean lines loaded"]];
  toLineE[DT6[a],{u,1}]];
toLineE[DT7[a_],{u,1}]:=Module[{},toLineE[DT7[temp1_],{u,1}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_7_euclidean_DT_u1_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 DT even u1 euclidean lines loaded"]];
  toLineE[DT7[a],{u,1}]];
toLineE[DT8[a_],{u,1}]:=Module[{},toLineE[DT8[temp1_],{u,1}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_8_euclidean_DT_u1_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 8 DT even u1 euclidean lines loaded"]];
  toLineE[DT8[a],{u,1}]];

toLineE[DT3[a_],{0,w}]:=Module[{},toLineE[DT3[temp1_],{0,w}]=.;
  toLineE[DT4[temp1_],{0,w}]=.;
  toLineE[DT5[temp1_],{0,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_5_euclidean_DT_0w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 0w euclidean lines loaded"]];
  toLineE[DT3[a],{0,w}]];
toLineE[DT4[a_],{0,w}]:=Module[{},toLineE[DT3[temp1_],{0,w}]=.;
  toLineE[DT4[temp1_],{0,w}]=.;
  toLineE[DT5[temp1_],{0,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_5_euclidean_DT_0w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 0w euclidean lines loaded"]];
  toLineE[DT4[a],{0,w}]];
toLineE[DT5[a_],{0,w}]:=Module[{},toLineE[DT3[temp1_],{0,w}]=.;
  toLineE[DT4[temp1_],{0,w}]=.;
  toLineE[DT5[temp1_],{0,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_5_euclidean_DT_0w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 0w euclidean lines loaded"]];
  toLineE[DT5[a],{0,w}]];
toLineE[DT6[a_],{0,w}]:=Module[{},toLineE[DT6[temp1_],{0,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_6_euclidean_DT_0w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 0w euclidean lines loaded"]];
  toLineE[DT6[a],{0,w}]];
toLineE[DT7[a_],{0,w}]:=Module[{},toLineE[DT7[temp1_],{0,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_7_euclidean_DT_0w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 DT even 0w euclidean lines loaded"]];
  toLineE[DT7[a],{0,w}]];
toLineE[DT8[a_],{0,w}]:=Module[{},toLineE[DT8[temp1_],{0,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_8_euclidean_DT_0w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 8 DT even 0w euclidean lines loaded"]];
  toLineE[DT8[a],{0,w}]];

toLineE[DT3[a_],{1,w}]:=Module[{},toLineE[DT3[temp1_],{1,w}]=.;
  toLineE[DT4[temp1_],{1,w}]=.;
  toLineE[DT5[temp1_],{1,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_5_euclidean_DT_1w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 1w euclidean lines loaded"]];
  toLineE[DT3[a],{1,w}]];
toLineE[DT4[a_],{1,w}]:=Module[{},toLineE[DT3[temp1_],{1,w}]=.;
  toLineE[DT4[temp1_],{1,w}]=.;
  toLineE[DT5[temp1_],{1,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_5_euclidean_DT_1w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 1w euclidean lines loaded"]];
  toLineE[DT4[a],{1,w}]];
toLineE[DT5[a_],{1,w}]:=Module[{},toLineE[DT3[temp1_],{1,w}]=.;
  toLineE[DT4[temp1_],{1,w}]=.;
  toLineE[DT5[temp1_],{1,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_5_euclidean_DT_1w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 1w euclidean lines loaded"]];
  toLineE[DT5[a],{1,w}]];
toLineE[DT6[a_],{1,w}]:=Module[{},toLineE[DT6[temp1_],{1,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_6_euclidean_DT_1w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 1w euclidean lines loaded"]];
  toLineE[DT6[a],{1,w}]];
toLineE[DT7[a_],{1,w}]:=Module[{},toLineE[DT7[temp1_],{1,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_7_euclidean_DT_1w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 DT even 1w euclidean lines loaded"]];
  toLineE[DT7[a],{1,w}]];
toLineE[DT8[a_],{1,w}]:=Module[{},toLineE[DT8[temp1_],{1,w}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_8_euclidean_DT_1w_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 8 DT even 1w euclidean lines loaded"]];
  toLineE[DT8[a],{1,w}]];

toLineE[DT3[a_],{0,0}]:=Module[{},toLineE[DT3[temp1_],{0,0}]=.;
  toLineE[DT4[temp1_],{0,0}]=.;
  toLineE[DT5[temp1_],{0,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_5_euclidean_DT_00_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 00 euclidean lines loaded"]];
  toLineE[DT3[a],{0,0}]];
toLineE[DT4[a_],{0,0}]:=Module[{},toLineE[DT3[temp1_],{0,0}]=.;
  toLineE[DT4[temp1_],{0,0}]=.;
  toLineE[DT5[temp1_],{0,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_5_euclidean_DT_00_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 00 euclidean lines loaded"]];
  toLineE[DT4[a],{0,0}]];
toLineE[DT5[a_],{0,0}]:=Module[{},toLineE[DT3[temp1_],{0,0}]=.;
  toLineE[DT4[temp1_],{0,0}]=.;
  toLineE[DT5[temp1_],{0,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_5_euclidean_DT_00_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 00 euclidean lines loaded"]];
  toLineE[DT5[a],{0,0}]];
toLineE[DT6[a_],{0,0}]:=Module[{},toLineE[DT6[temp1_],{0,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_6_euclidean_DT_00_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 00 euclidean lines loaded"]];
  toLineE[DT6[a],{0,0}]];
toLineE[DT7[a_],{0,0}]:=Module[{},toLineE[DT7[temp1_],{0,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_7_euclidean_DT_00_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 DT even 00 euclidean lines loaded"]];
  toLineE[DT7[a],{0,0}]];
toLineE[DT8[a_],{0,0}]:=Module[{},toLineE[DT8[temp1_],{0,0}]=.;
  Get[$MathematicaLibrary<>"/Function Library/DT Limits/Local Binaries/weight_8_euclidean_DT_00_lines_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 8 DT even 00 euclidean lines loaded"]];
  toLineE[DT8[a],{0,0}]];
