(* ::Package:: *)

irrToGI[H3[a_]]:=Module[{},irrToGI[H3[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 3/Local Binaries/weight_3_irreducible_GI_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 3 GI functions loaded"]];
  irrToGI[H3[a]]];
irrToGI[H4[a_]]:=Module[{},irrToGI[H4[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 4/Local Binaries/weight_4_irreducible_GI_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 4 GI functions loaded"]];
  irrToGI[H4[a]]];
irrToGI[H5[a_]]:=Module[{},irrToGI[H5[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 5/Local Binaries/weight_5_irreducible_GI_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 GI functions loaded"]];
  irrToGI[H5[a]]];
irrToGI[H6[a_]]:=Module[{},irrToGI[H6[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 6/Local Binaries/weight_6_irreducible_GI_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 GI functions loaded"]];
  irrToGI[H6[a]]];
irrToGI[E7[a_]]:=Module[{},irrToGI[E7[temp_]]=.;
  irrToGI[O7[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 7/Local Binaries/weight_7_irreducible_GI_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 GI functions loaded"]];
  irrToGI[E7[a]]];
irrToGI[O7[a_]]:=Module[{},irrToGI[E7[temp_]]=.;
  irrToGI[O7[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 7/Local Binaries/weight_7_irreducible_GI_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 GI functions loaded"]];
  irrToGI[O7[a]]];

irrToGII[H3[a_]]:=Module[{},irrToGII[H3[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 3/Local Binaries/weight_3_irreducible_GII_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 3 GII functions loaded"]];
  irrToGII[H3[a]]];
irrToGII[H4[a_]]:=Module[{},irrToGII[H4[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 4/Local Binaries/weight_4_irreducible_GII_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 4 GII functions loaded"]];
  irrToGII[H4[a]]];
irrToGII[H5[a_]]:=Module[{},irrToGII[H5[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 5/Local Binaries/weight_5_irreducible_GII_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 GII functions loaded"]];
  irrToGII[H5[a]]];
irrToGII[H6[a_]]:=Module[{},irrToGII[H6[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 6/Local Binaries/weight_6_irreducible_GII_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 GII functions loaded"]];
  irrToGII[H6[a]]];
irrToGII[E7[a_]]:=Module[{},irrToGII[E7[temp_]]=.;
  irrToGII[O7[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 7/Local Binaries/weight_7_irreducible_GII_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 GII functions loaded"]];
  irrToGII[E7[a]]];
irrToGII[O7[a_]]:=Module[{},irrToGII[E7[temp_]]=.;
  irrToGII[O7[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 7/Local Binaries/weight_7_irreducible_GII_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 GII functions loaded"]];
  irrToGII[O7[a]]];

irrToDSG[DS3[a_]]:=Module[{},irrToDSG[DS3[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 3/Local Binaries/weight_3_irreducible_DSG_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 3 DSG functions loaded"]];
  irrToDSG[DS3[a]]];
irrToDSG[DS4[a_]]:=Module[{},irrToDSG[DS4[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 4/Local Binaries/weight_4_irreducible_DSG_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 4 DSG functions loaded"]];
  irrToDSG[DS4[a]]];
irrToDSG[DS5[a_]]:=Module[{},irrToDSG[DS5[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 5/Local Binaries/weight_5_irreducible_DSG_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 DSG functions loaded"]];
  irrToDSG[DS5[a]]];
irrToDSG[DS6[a_]]:=Module[{},irrToDSG[DS6[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 6/Local Binaries/weight_6_irreducible_DSG_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 DSG functions loaded"]];
  irrToDSG[DS6[a]]];
irrToDSG[DS7[a_]]:=Module[{},irrToDSG[DS7[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 7/Local Binaries/weight_7_irreducible_DSG_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 DSG functions loaded"]];
  irrToDSG[DS7[a]]];
irrToDSG[DS8[a_]]:=Module[{},irrToDSG[DS8[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 8/Local Binaries/weight_8_irreducible_DSG_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 8 DSG functions loaded"]];
  irrToDSG[DS8[a]]];

irrToSPG[SP2[a_]]:=Module[{},irrToSPG[SP2[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 2/Local Binaries/weight_2_irreducible_SPG_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 2 SPG functions loaded"]];
  irrToSPG[SP2[a]]];
irrToSPG[SP3[a_]]:=Module[{},irrToSPG[SP3[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 3/Local Binaries/weight_3_irreducible_SPG_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 3 SPG functions loaded"]];
  irrToSPG[SP3[a]]];
irrToSPG[SP4[a_]]:=Module[{},irrToSPG[SP4[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 4/Local Binaries/weight_4_irreducible_SPG_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 4 SPG functions loaded"]];
  irrToSPG[SP4[a]]];
irrToSPG[SP5[a_]]:=Module[{},irrToSPG[SP5[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 5/Local Binaries/weight_5_irreducible_SPG_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 5 SPG functions loaded"]];
  irrToSPG[SP5[a]]];
irrToSPG[SP6[a_]]:=Module[{},irrToSPG[SP6[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 6/Local Binaries/weight_6_irreducible_SPG_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 6 SPG functions loaded"]];
  irrToSPG[SP6[a]]];
irrToSPG[SP7[a_]]:=Module[{},irrToSPG[SP7[temp_]]=.;
  Get[$MathematicaLibrary<>"/Function Library/Weight 7/Local Binaries/weight_7_irreducible_SPG_functions_"<>ToString[Floor[$VersionNumber]]<>".mx"];
  If[debug,Print["weight 7 SPG functions loaded"]];
  irrToSPG[SP7[a]]];
